---
apiVersion: v1
items:
- apiVersion: postgresql.cnpg.io/v1
  kind: Cluster
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","metadata":{"annotations":{},"name":"cluster-example","namespace":"default"},"spec":{"instances":3,"storage":{"size":"1Gi"}}}
    creationTimestamp: "2026-03-11T09:12:49Z"
    generation: 1
    name: cluster-example
    namespace: default
    resourceVersion: "989362"
    uid: 2b344063-6b53-41d2-b4be-4c19fa099408
  spec:
    affinity:
      podAntiAffinityType: preferred
    bootstrap:
      initdb:
        database: app
        encoding: UTF8
        localeCType: C
        localeCollate: C
        owner: app
    enablePDB: true
    enableSuperuserAccess: false
    failoverDelay: 0
    imageName: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie
    instances: 3
    logLevel: info
    maxSyncReplicas: 0
    minSyncReplicas: 0
    monitoring:
      customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
      disableDefaultQueries: false
      enablePodMonitor: false
    postgresGID: 26
    postgresUID: 26
    postgresql:
      parameters:
        archive_mode: "on"
        archive_timeout: 5min
        dynamic_shared_memory_type: posix
        full_page_writes: "on"
        log_destination: csvlog
        log_directory: /controller/log
        log_filename: postgres
        log_rotation_age: "0"
        log_rotation_size: "0"
        log_truncate_on_rotation: "false"
        logging_collector: "on"
        max_parallel_workers: "32"
        max_replication_slots: "32"
        max_worker_processes: "32"
        shared_memory_type: mmap
        shared_preload_libraries: ""
        ssl_max_protocol_version: TLSv1.3
        ssl_min_protocol_version: TLSv1.3
        wal_keep_size: 512MB
        wal_level: logical
        wal_log_hints: "on"
        wal_receiver_timeout: 5s
        wal_sender_timeout: 5s
      syncReplicaElectionConstraint:
        enabled: false
    primaryUpdateMethod: restart
    primaryUpdateStrategy: unsupervised
    probes:
      liveness:
        isolationCheck:
          connectionTimeout: 1000
          enabled: true
          requestTimeout: 1000
    replicationSlots:
      highAvailability:
        enabled: true
        slotPrefix: _cnpg_
      synchronizeReplicas:
        enabled: true
      updateInterval: 30
    resources: {}
    smartShutdownTimeout: 180
    startDelay: 3600
    stopDelay: 1800
    storage:
      resizeInUseVolumes: true
      size: 1Gi
    switchoverDelay: 3600
  status:
    availableArchitectures:
    - goArch: amd64
      hash: 1fa32bddc89d8eb9de4a448660db1f1d0227e0269b4ffdcb98e6dbbcffe12cf9
    - goArch: arm64
      hash: e340717194993e45f026a61c78a424a5eba6a3b628e6c2d1d617ae1a94a58ee0
    certificates:
      clientCASecret: cluster-example-ca
      expirations:
        cluster-example-ca: 2026-06-09 09:07:49 +0000 UTC
        cluster-example-replication: 2026-06-09 09:07:49 +0000 UTC
        cluster-example-server: 2026-06-09 09:07:49 +0000 UTC
      replicationTLSSecret: cluster-example-replication
      serverAltDNSNames:
      - cluster-example-rw
      - cluster-example-rw.default
      - cluster-example-rw.default.svc
      - cluster-example-rw.default.svc.cluster.local
      - cluster-example-r
      - cluster-example-r.default
      - cluster-example-r.default.svc
      - cluster-example-r.default.svc.cluster.local
      - cluster-example-ro
      - cluster-example-ro.default
      - cluster-example-ro.default.svc
      - cluster-example-ro.default.svc.cluster.local
      serverCASecret: cluster-example-ca
      serverTLSSecret: cluster-example-server
    cloudNativePGCommitHash: 1ecc48340
    cloudNativePGOperatorHash: e340717194993e45f026a61c78a424a5eba6a3b628e6c2d1d617ae1a94a58ee0
    conditions:
    - lastTransitionTime: "2026-03-11T09:18:11Z"
      message: A single, unique system ID was found across reporting instances.
      reason: Unique
      status: "True"
      type: ConsistentSystemID
    - lastTransitionTime: "2026-03-11T09:18:57Z"
      message: Cluster is Ready
      reason: ClusterIsReady
      status: "True"
      type: Ready
    - lastTransitionTime: "2026-03-11T09:18:10Z"
      message: Continuous archiving is working
      reason: ContinuousArchivingSuccess
      status: "True"
      type: ContinuousArchiving
    configMapResourceVersion:
      metrics:
        cnpg-default-monitoring: "1277"
    currentPrimary: cluster-example-1
    currentPrimaryTimestamp: "2026-03-11T09:18:10.779382Z"
    healthyPVC:
    - cluster-example-1
    - cluster-example-2
    - cluster-example-3
    image: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie
    instanceNames:
    - cluster-example-1
    - cluster-example-2
    - cluster-example-3
    instances: 3
    instancesReportedState:
      cluster-example-1:
        ip: 10.244.0.3
        isPrimary: true
        timeLineID: 1
      cluster-example-2:
        ip: 10.244.0.6
        isPrimary: false
        timeLineID: 1
      cluster-example-3:
        ip: 10.244.0.4
        isPrimary: false
        timeLineID: 1
    instancesStatus:
      healthy:
      - cluster-example-1
      - cluster-example-2
      - cluster-example-3
    latestGeneratedNode: 3
    managedRolesStatus: {}
    pgDataImageInfo:
      image: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie
      majorVersion: 18
    phase: Cluster in healthy state
    poolerIntegrations:
      pgBouncerIntegration: {}
    pvcCount: 3
    readService: cluster-example-r
    readyInstances: 3
    secretsResourceVersion:
      applicationSecretVersion: "1249"
      clientCaSecretVersion: "1246"
      replicationSecretVersion: "1248"
      serverCaSecretVersion: "1246"
      serverSecretVersion: "1247"
    switchReplicaClusterStatus: {}
    systemID: "7615924853513093149"
    targetPrimary: cluster-example-1
    targetPrimaryTimestamp: "2026-03-11T09:12:50.032149Z"
    timelineID: 1
    topology:
      instances:
        cluster-example-1: {}
        cluster-example-2: {}
        cluster-example-3: {}
      nodesUsed: 1
      successfullyExtracted: true
    writeService: cluster-example-rw
- apiVersion: postgresql.cnpg.io/v1
  kind: Cluster
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","metadata":{"annotations":{},"name":"image-example","namespace":"default"},"spec":{"imageName":"ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie","instances":1,"postgresql":{"extensions":[{"image":{"reference":"ghcr.io/cloudnative-pg/pgvector:0.8.1-18-trixie"},"name":"pgvector"}]},"storage":{"size":"1Gi"}}}
    creationTimestamp: "2026-03-11T10:15:22Z"
    generation: 1
    name: image-example
    namespace: default
    resourceVersion: "989367"
    uid: e4f52441-79c0-4f23-bd1d-82a02b6fa86c
  spec:
    affinity:
      podAntiAffinityType: preferred
    bootstrap:
      initdb:
        database: app
        encoding: UTF8
        localeCType: C
        localeCollate: C
        owner: app
    enablePDB: true
    enableSuperuserAccess: false
    failoverDelay: 0
    imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie
    instances: 1
    logLevel: info
    maxSyncReplicas: 0
    minSyncReplicas: 0
    monitoring:
      customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
      disableDefaultQueries: false
      enablePodMonitor: false
    postgresGID: 26
    postgresUID: 26
    postgresql:
      extensions:
      - image:
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.1-18-trixie
        name: pgvector
      parameters:
        archive_mode: "on"
        archive_timeout: 5min
        dynamic_shared_memory_type: posix
        full_page_writes: "on"
        log_destination: csvlog
        log_directory: /controller/log
        log_filename: postgres
        log_rotation_age: "0"
        log_rotation_size: "0"
        log_truncate_on_rotation: "false"
        logging_collector: "on"
        max_parallel_workers: "32"
        max_replication_slots: "32"
        max_worker_processes: "32"
        shared_memory_type: mmap
        shared_preload_libraries: ""
        ssl_max_protocol_version: TLSv1.3
        ssl_min_protocol_version: TLSv1.3
        wal_keep_size: 512MB
        wal_level: logical
        wal_log_hints: "on"
        wal_receiver_timeout: 5s
        wal_sender_timeout: 5s
      syncReplicaElectionConstraint:
        enabled: false
    primaryUpdateMethod: restart
    primaryUpdateStrategy: unsupervised
    probes:
      liveness:
        isolationCheck:
          connectionTimeout: 1000
          enabled: true
          requestTimeout: 1000
    replicationSlots:
      highAvailability:
        enabled: true
        slotPrefix: _cnpg_
      synchronizeReplicas:
        enabled: true
      updateInterval: 30
    resources: {}
    smartShutdownTimeout: 180
    startDelay: 3600
    stopDelay: 1800
    storage:
      resizeInUseVolumes: true
      size: 1Gi
    switchoverDelay: 3600
  status:
    availableArchitectures:
    - goArch: amd64
      hash: 1fa32bddc89d8eb9de4a448660db1f1d0227e0269b4ffdcb98e6dbbcffe12cf9
    - goArch: arm64
      hash: e340717194993e45f026a61c78a424a5eba6a3b628e6c2d1d617ae1a94a58ee0
    certificates:
      clientCASecret: image-example-ca
      expirations:
        image-example-ca: 2026-06-09 10:10:22 +0000 UTC
        image-example-replication: 2026-06-09 10:10:22 +0000 UTC
        image-example-server: 2026-06-09 10:10:22 +0000 UTC
      replicationTLSSecret: image-example-replication
      serverAltDNSNames:
      - image-example-rw
      - image-example-rw.default
      - image-example-rw.default.svc
      - image-example-rw.default.svc.cluster.local
      - image-example-r
      - image-example-r.default
      - image-example-r.default.svc
      - image-example-r.default.svc.cluster.local
      - image-example-ro
      - image-example-ro.default
      - image-example-ro.default.svc
      - image-example-ro.default.svc.cluster.local
      serverCASecret: image-example-ca
      serverTLSSecret: image-example-server
    cloudNativePGCommitHash: 1ecc48340
    cloudNativePGOperatorHash: e340717194993e45f026a61c78a424a5eba6a3b628e6c2d1d617ae1a94a58ee0
    conditions:
    - lastTransitionTime: "2026-03-11T10:16:02Z"
      message: A single, unique system ID was found across reporting instances.
      reason: Unique
      status: "True"
      type: ConsistentSystemID
    - lastTransitionTime: "2026-03-11T10:16:11Z"
      message: Cluster is Ready
      reason: ClusterIsReady
      status: "True"
      type: Ready
    - lastTransitionTime: "2026-03-11T10:16:02Z"
      message: Continuous archiving is working
      reason: ContinuousArchivingSuccess
      status: "True"
      type: ContinuousArchiving
    configMapResourceVersion:
      metrics:
        cnpg-default-monitoring: "1277"
    currentPrimary: image-example-1
    currentPrimaryTimestamp: "2026-03-11T10:16:01.983580Z"
    healthyPVC:
    - image-example-1
    image: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie
    instanceNames:
    - image-example-1
    instances: 1
    instancesReportedState:
      image-example-1:
        ip: 10.244.0.5
        isPrimary: true
        timeLineID: 1
    instancesStatus:
      healthy:
      - image-example-1
    latestGeneratedNode: 1
    managedRolesStatus: {}
    pgDataImageInfo:
      image: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie
      majorVersion: 18
    phase: Cluster in healthy state
    poolerIntegrations:
      pgBouncerIntegration: {}
    pvcCount: 1
    readService: image-example-r
    readyInstances: 1
    secretsResourceVersion:
      applicationSecretVersion: "7552"
      clientCaSecretVersion: "7549"
      replicationSecretVersion: "7551"
      serverCaSecretVersion: "7549"
      serverSecretVersion: "7550"
    switchReplicaClusterStatus: {}
    systemID: "7615939760483057693"
    targetPrimary: image-example-1
    targetPrimaryTimestamp: "2026-03-11T10:15:23.044227Z"
    timelineID: 1
    topology:
      instances:
        image-example-1: {}
      nodesUsed: 1
      successfullyExtracted: true
    writeService: image-example-rw
kind: List
metadata:
  resourceVersion: ""
